# Generated by Django 5.0.4 on 2024-05-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Счётчик просмотров"
            ),
        ),
    ]
