# Generated by Django 4.2.2 on 2024-06-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_options_product_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.IntegerField(verbose_name="Цена за покупку"),
        ),
    ]
